version: '3.8'

services:
  weather-service:
    build: ./apps/weather-service
    ports:
      - '50051:50051'
    depends_on:
      - redis
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      WEATHER_API_BASE_URL: ${WEATHER_API_BASE_URL}
      OWM_API_KEY: ${OWM_API_KEY}
      OWM_API_BASE_URL: ${OWM_API_BASE_URL}
    networks:
      - backend
    volumes:
      - ./apps/proto:/proto

  subscription-service:
    build: ./apps/subscription-service
    ports:
      - '50052:50052'
    depends_on:
      - postgres
      - rabbitmq
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    networks:
      - backend
    volumes:
      - ./apps/proto:/proto

  notification-service:
    build: apps/notification-service
    ports:
      - '50053:50053'
    depends_on:
      - rabbitmq
    environment:
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      WEATHER_SERVICE_ADDRESS: ${WEATHER_SERVICE_ADDRESS}
    networks:
      - backend
    volumes:
      - ./apps/proto:/proto

  api-gateway:
    build: ./apps/api-gateway
    ports:
      - '3001:3001'
    depends_on:
      - subscription-service
      - weather-service
      - notification-service
    environment:
      APIGATEWAY_PORT: ${APIGATEWAY_PORT}
      SUBSCRIPTION_SERVICE_ADDRESS: ${SUBSCRIPTION_SERVICE_ADDRESS}
      WEATHER_SERVICE_ADDRESS: ${WEATHER_SERVICE_ADDRESS}
    networks:
      - backend
    volumes:
      - ./apps/proto:/proto

  postgres:
    image: postgres:14
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  pgdata:

networks:
  backend:
    driver: bridge
