version: '3.8'

services:
  weather-service:
    build: ./apps/weather-service
    depends_on:
      - redis
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      WEATHER_API_BASE_URL: ${WEATHER_API_BASE_URL}
      OWM_API_KEY: ${OWM_API_KEY}
      OWM_API_BASE_URL: ${OWM_API_BASE_URL}
    networks:
      - backend
    volumes:
      - ./apps/proto:/proto

  subscription-service:
    build: ./apps/subscription-service
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      RABBITMQ_URL: ${RABBITMQ_URL}
    networks:
      - backend
    volumes:
      - ./apps/proto:/proto

  notification-service:
    build: apps/notification-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      WEATHER_SERVICE_ADDRESS: ${WEATHER_SERVICE_ADDRESS}
      RABBITMQ_URL: ${RABBITMQ_URL}
    networks:
      - backend
    volumes:
      - ./apps/proto:/proto

  api-gateway:
    build: ./apps/api-gateway
    ports:
      - '3001:3001'
    depends_on:
      - weather-service
      - subscription-service
      - notification-service
    environment:
      APIGATEWAY_PORT: ${APIGATEWAY_PORT}
      WEATHER_SERVICE_ADDRESS: ${WEATHER_SERVICE_ADDRESS}
      SUBSCRIPTION_SERVICE_ADDRESS: ${SUBSCRIPTION_SERVICE_ADDRESS}
    networks:
      - backend
    volumes:
      - ./apps/proto:/proto

  postgres:
    image: postgres:14
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata-test:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  e2e-tests:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    depends_on:
      - api-gateway
    networks:
      - backend
    environment:
      PLAYWRIGHT_TEST_BASE_URL: ${PLAYWRIGHT_TEST_BASE_URL}
    volumes:
      - ./test/e2e:/app/test/e2e

volumes:
  pgdata-test:

networks:
  backend:
    driver: bridge
