version: '3.8'

services:
  weather-service:
    build: ./apps/weather-service
    ports:
      - '50051:50051'
    depends_on:
      - redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - backend
    volumes:
      - ./apps/proto:/proto

  subscription-service:
    build: ./apps/subscription-service
    ports:
      - '50052:50052'
    depends_on:
      - postgres
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - MAILER_SERVICE_ADDRESS=${MAILER_SERVICE_ADDRESS}
    networks:
      - backend
    volumes:
      - ./apps/proto:/proto

  mailer-service:
    build: ./apps/mailer-service
    ports:
      - '50053:50053'
    environment:
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - WEATHER_SERVICE_ADDRESS=${WEATHER_SERVICE_ADDRESS}
      - SUBSCRIPTION_SERVICE_ADDRESS=${SUBSCRIPTION_SERVICE_ADDRESS}
    networks:
      - backend
    volumes:
      - ./apps/proto:/proto

  api-gateway:
    build: ./apps/api-gateway
    ports:
      - '3001:3001'
    depends_on:
      - subscription-service
      - weather-service
      - mailer-service
    environment:
      - SUBSCRIPTION_SERVICE_ADDRESS=${SUBSCRIPTION_SERVICE_ADDRESS}
      - WEATHER_SERVICE_ADDRESS=${WEATHER_SERVICE_ADDRESS}
      - MAILER_SERVICE_ADDRESS=${MAILER_SERVICE_ADDRESS}
    networks:
      - backend
    volumes:
      - ./apps/proto:/proto

  postgres:
    image: postgres:14
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: bridge
