services:
  test_db:
    image: postgres:14
    container_name: test_weather_db
    env_file:
      - .env.test
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - pgtestdata:/var/lib/postgresql/data

  test_runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: test_runner
    env_file:
      - .env.test
    depends_on:
      test_db:
        condition: service_healthy
      redis:
        condition: service_started
    command: npm test

  redis:
    image: redis:7
    container_name: test_weather_redis
    ports:
      - "6380:6379"

  playwright_runner:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    container_name: playwright_runner
    env_file:
      - .env.test
    depends_on:
      test_db:
        condition: service_healthy
      redis:
        condition: service_started

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: test_migrator
    env_file:
      - .env.test
    depends_on:
      test_db:
        condition: service_healthy
      redis:
        condition: service_started
    command: sh -c "npx sequelize-cli db:migrate --config src/db/config/config.js"

volumes:
  pgtestdata: