name: CI

on: [push, pull_request]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build and run containers
        run: docker compose --env-file .env.test -f docker-compose.test.yml up -d --build

      - name: Wait for services to be ready
        run: sleep 15

      - name: Run E2E tests
        run: docker compose --env-file .env.test -f docker-compose.test.yml run --rm e2e-tests

      - name: Shutdown containers
        if: always()
        run: docker compose --env-file .env.test -f docker-compose.test.yml down --volumes --remove-orphans
