name: Run Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Unit Tests
        run: docker-compose --env-file .env.test -f docker-compose.test.yml run --rm test_runner npm run test:unit

  test-integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Integration Tests
        run: docker-compose --env-file .env.test -f docker-compose.test.yml run --rm test_runner npm run test:integration

  test-e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run E2E Tests
        run: docker-compose --env-file .env.test -f docker-compose.test.yml run --rm playwright_runner npm run test:e2e
