name: CI Tests

on:
  push:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Unit Tests
        run: docker compose -f docker-compose.test.yml run --rm test_runner npm run test:unit

  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start database
        run: docker compose -f docker-compose.test.yml up -d test_db

      - name: Run DB migrations
        run: docker compose -f docker-compose.test.yml run --rm test_runner npx sequelize-cli db:migrate --config src/db/config/config.js

      - name: Run Integration Tests
        run: docker compose -f docker-compose.test.yml run --rm test_runner npm run test:integration

  e2e_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run E2E Tests
        run: docker compose -f docker-compose.test.yml run --rm playwright_runner npm run test:e2e
